<?php

return [
    'tokens' => [
        'access_ttl_seconds' => (int) (getenv('AUTH_ACCESS_TOKEN_TTL') ?: 900),
        'refresh_ttl_seconds' => (int) (getenv('AUTH_REFRESH_TOKEN_TTL') ?: 2592000),
        'password_reset_ttl_seconds' => (int) (getenv('AUTH_PASSWORD_RESET_TTL') ?: 3600),
        'refresh_token_bytes' => (int) (getenv('AUTH_REFRESH_TOKEN_BYTES') ?: 32),
        'access_token_secret' => getenv('AUTH_ACCESS_TOKEN_SECRET') ?: 'fox-platform-local-secret',
    ],
    'guards' => [
        'admin',
        'partner',
        'driver',
    ],
    'roles' => [
        'super_admin',
        'admin_operacional',
        'admin_financeiro',
        'admin_comercial',
        'suporte',
        'partner_owner',
        'partner_manager',
        'partner_staff',
        'driver',
    ],
    'permission_modules' => [
        'dashboard',
        'orders',
        'catalog',
        'inventory',
        'marketing',
        'finance',
        'store',
        'team',
        'reviews',
        'support',
        'reports',
        'settings',
        'approvals',
    ],
    'permission_actions' => [
        'view',
        'create',
        'update',
        'delete',
        'manage',
        'approve',
        'export',
    ],
];
