<?php

return [
    'auth' => [
        'POST /api/v1/auth/login',
        'POST /api/v1/auth/refresh',
        'POST /api/v1/auth/logout',
        'POST /api/v1/auth/forgot-password',
        'POST /api/v1/auth/reset-password',
        'GET /api/v1/auth/me',
    ],
    'admin' => [
        'GET /api/v1/admin/dashboard',
        'GET /api/v1/admin/finance/overview',
        'GET /api/v1/admin/orders',
        'GET /api/v1/admin/approvals/partners',
        'GET /api/v1/admin/approvals/drivers',
        'POST /api/v1/admin/approvals/partners/{partner_id}/approve',
        'POST /api/v1/admin/approvals/partners/{partner_id}/reject',
        'POST /api/v1/admin/approvals/drivers/{driver_id}/approve',
        'POST /api/v1/admin/approvals/drivers/{driver_id}/reject',
        'GET /api/v1/admin/support/queue',
        'GET /api/v1/admin/settings',
        'PUT /api/v1/admin/settings',
    ],
    'partner' => [
        'GET /api/v1/partner/profile',
        'PUT /api/v1/partner/profile',
        'GET /api/v1/partner/store',
        'PUT /api/v1/partner/store',
        'PUT /api/v1/partner/store/hours',
        'POST /api/v1/partner/store/documents',
        'GET /api/v1/partner/dashboard',
        'GET /api/v1/partner/finance/summary',
        'GET /api/v1/partner/orders',
        'PUT /api/v1/partner/orders/{order_id}/status',
        'GET /api/v1/partner/catalog/products',
        'POST /api/v1/partner/catalog/products',
        'PUT /api/v1/partner/catalog/products/{product_id}',
        'PUT /api/v1/partner/catalog/products/{product_id}/inventory',
        'GET /api/v1/partner/team',
        'POST /api/v1/partner/team',
        'PUT /api/v1/partner/team/{member_id}',
        'PUT /api/v1/partner/team/{member_id}/status',
        'GET /api/v1/partner/support',
        'GET /api/v1/partner/support/{ticket_id}',
        'POST /api/v1/partner/support/tickets',
        'POST /api/v1/partner/support/{ticket_id}/messages',
        'GET /api/v1/partner/notifications',
        'POST /api/v1/partner/notifications/{notification_id}/read',
    ],
    'driver' => [
        'GET /api/v1/driver/dashboard',
        'GET /api/v1/driver/profile',
        'PUT /api/v1/driver/profile',
        'GET /api/v1/driver/earnings',
        'GET /api/v1/driver/availability',
        'GET /api/v1/driver/documents',
        'GET /api/v1/driver/support',
        'GET /api/v1/driver/support/{ticket_id}',
        'POST /api/v1/driver/support/tickets',
        'POST /api/v1/driver/support/{ticket_id}/messages',
        'GET /api/v1/driver/notifications',
        'POST /api/v1/driver/notifications/{notification_id}/read',
    ],
    'public' => [
        'GET /api/v1/public/categories',
        'GET /api/v1/public/platform-metrics',
        'POST /api/v1/public/partner-leads',
        'POST /api/v1/public/driver-leads',
    ],
];
