<?php

return [
    'auth' => [
        'POST /api/v1/auth/login',
        'POST /api/v1/auth/refresh',
        'POST /api/v1/auth/logout',
        'POST /api/v1/auth/forgot-password',
        'POST /api/v1/auth/reset-password',
        'GET /api/v1/auth/me',
    ],
    'admin' => [
        'GET /api/v1/admin/dashboard',
        'GET /api/v1/admin/partners',
        'GET /api/v1/admin/drivers',
        'GET /api/v1/admin/orders',
        'GET /api/v1/admin/finance/overview',
        'GET /api/v1/admin/reports/overview',
        'GET /api/v1/admin/support',
        'GET /api/v1/admin/audit',
        'GET /api/v1/admin/analytics',
    ],
    'partner' => [
        'GET /api/v1/partner/profile',
        'PUT /api/v1/partner/profile',
        'GET /api/v1/partner/store',
        'PUT /api/v1/partner/store',
        'PUT /api/v1/partner/store/hours',
        'POST /api/v1/partner/store/documents',
        'GET /api/v1/partner/dashboard',
        'GET /api/v1/partner/orders',
        'GET /api/v1/partner/catalog/products',
        'GET /api/v1/partner/finance/summary',
        'GET /api/v1/partner/messages',
        'GET /api/v1/partner/support',
        'GET /api/v1/partner/help',
    ],
    'driver' => [
        'GET /api/v1/driver/dashboard',
        'GET /api/v1/driver/profile',
        'GET /api/v1/driver/earnings',
        'GET /api/v1/driver/availability',
        'GET /api/v1/driver/support',
    ],
    'public' => [
        'GET /api/v1/public/categories',
        'GET /api/v1/public/platform-metrics',
        'POST /api/v1/public/partner-leads',
        'POST /api/v1/public/driver-leads',
    ],
];
